name: Test Stronk with Vitest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.2'

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npx vitest run ./tests